### ISSUE TITLE
Can't untoggle the top two toggles (CP) on Settings page

### ISSUE THREAD

**Issue by hickman-santini** [Metaculus/metaculus#426]
**We should either decide we don't want this or implement it like it is on prod. I think it's important to implement; any arguments against?**

@ncarazon commented on the [notion](https://www.notion.so/metaculus/Can-t-untoggle-the-top-two-under-CP-83cdec84c17342eca1796539381a1305?pvs=4) issue:

> we need to add a field on the BE to store these settings or do we want to just store it in local storage? Also, is there a spec on what each flag should do in the app?

## Current behavior
These two are untoggleable:

![image(9)](https://github.com/user-attachments/assets/9a7e5243-6b20-48d9-85d6-e62fd304a2b7)

## Expected/desired behavior
“Show CP by default on open questions” is true by default; if false, the CP graphs are all blank (on the home page and if you click into the question). E.g. see screenshot.

![image(10)](https://github.com/user-attachments/assets/e3021107-a029-4272-8ea6-92de6e44189b)

“Show CP if you’ve predicted” is the same, but once you’ve made one prediction, the CP is revealed (appears as normal, on home page and question page). The point is some people don’t want to be anchored by the CP before they’ve thought about a question themself.

Also, if you’ve hidden them, you should get text under the graph on the question page like this, linking you to the settings page: 

![image(11)](https://github.com/user-attachments/assets/68aed291-66cd-4563-9ae1-b38af8dd1013)

**Comment by George3d6** [comment]
Ok, so basically:
1 option which is "hide CP"
and when the CP is hidden due to this option we show a button on the graph that says "Reveal CP" & Allows the user to temporarily do that.

**Comment by George3d6** [comment]
New option added

**Comment by hickman-santini** [comment]
CP time series is hidden (great!) on main feed and question page, but I can still see it under Make a Prediction, which kind of defeats the purpose.

![image](https://github.com/user-attachments/assets/6a9fd7ef-3c08-4488-bff4-55a977a6d50d)
(this is true of all question types; just showing continuous since I expect that's the hardest one to fix)

## On prod
Fwiw I notice this doesn't _really_ work on prod either (so maybe we can just let it be for now / not block release) -- only works for some question types, like:
<img src="https://github.com/user-attachments/assets/d47db817-a97e-4b62-85c5-afd5ebe74e0c" width="60%">

But it does hide the CP under "Make a Prediction."
<img src="https://github.com/user-attachments/assets/ae6056ef-522c-407a-80b4-3efbff464f93" width="60%">

**Comment by hickman-santini** [comment]
@hlibowski @lsabor I would love to make it so that you can't see the CP at all on the question page, like last screenshot above and https://www.metaculus.com/questions/28163/gas-price-at-end-of-sept-2024/:
![image](https://github.com/user-attachments/assets/147a24bd-43ec-4101-93f2-80b9d01ef09b)

How annoying would this be to implement.

**Comment by lsabor** [comment]
@hlibowski is the toggle functioning properly?
If so - removing the cp column from that display should be extremely easy.

**Comment by lsabor** [comment]
I have to correct myself, the method to reveal the CP is embedded in the graph component which would then have to talk with the forecast input component, which is not trivial and would require some refactoring.
I was expecting that when the CP is hidden we don't actually return populated CP values and we could just retrieve the values at will if we want to temporarily reveal it, but instead it looks like we have the data and hide it and so it will require some more complicated state management.

**Comment by lsabor** [comment]
For now, I'm going to have the forecast maker respect the user's setting. Awkwardly, that means that the forecast maker won't respect the "temporarily reveal" button in the graph.

**Comment by lsabor** [comment]
I've implemented and merged this. The drawback to my solution is (just as I suggested) that it doesn't respect the "temporary reaveal" button. A future refactor will be required, but this does allow users with the setting on to successfully hide it from themselves for now. Moving to medium priority for addressing the straggling issue as it's no longer blocking.

I'd still like to just not return the CP details at all with the setting on and never make any checks about displaying - there are too many locations to add the conditions.

**Comment by hickman-santini** [comment]
On dev I still see the CP, e.g. [here](https://dev.metaculus.com/questions/384/)
![image](https://github.com/user-attachments/assets/3a44b065-f23b-4b20-b5c0-35f801445c9e)

and [here](https://dev.metaculus.com/questions/3479/)
![image](https://github.com/user-attachments/assets/b482a4ae-9c6e-432a-b52d-afa1c1aeae52)

**Comment by hickman-santini** [comment]
Closing this out since the toggle has an effect now...! and I'll make a new issue for respecting "temporarily reveal," which like @lsabor said will take significant effort and can wait until after launch.
